### ISSUE TITLE
Send credentials

### ISSUE THREAD

**Issue by phwegner** [lhncbc/fhir-obs-viewer#10]
Dear all, 

how can I alter the code to make every request send the Credentials stored in the cookies with it? 

My FHIR server is protected by a NGINX basic auth but I would really like to use the fhir-obs-viewer. 

Thanks in advance!

**Comment by plynchnlm** [comment]
After you collect the user name and password from the user (however you are planning to do that), you would want to create and store the Authorization header like we do here:

https://github.com/lhncbc/fhir-obs-viewer/blob/master/src/app/shared/fhir-backend/fhir-backend.service.ts#L344

Does that help?

**Comment by phwegner** [comment]
The username and password are cached and I just need to add the withCredentials property to the requests, such as in the following example:
```
ajax({
    url: "yoururl",
    type: "GET",
    dataType: 'json',
    xhrFields: {
         withCredentials: true
    }
});
```

And I'm wondering where in the code I can do the appropriate changes.

**Comment by phwegner** [comment]
What I have tried so far: 
- I have added the option for sending credentials in the file src/app/shared/fhir-backend/fhir-backend.service.ts in the following way: 
```
return new Observable<HttpResponse<any>>(
      (observer: Observer<HttpResponse<any>>) => {
        this.fhirClient.initialize().then(() => {
          // Requests to the FHIR server without endpoint cannot be combined
          // into a batch request
          const combine =
            this.fhirClient.getFeatures().batch &&
            serviceBaseUrlWithEndpoint.test(newRequest.url);
          const promise = this.isCacheEnabled
            ? this.fhirClient.getWithCache(fullUrl, {
                combine,
                signal,
                cacheName: cacheName
                  ? cacheName + '-' + this.serviceBaseUrl
                  : '',
                withCredentials: true
              })
            : this.fhirClient.get(fullUrl, { combine, signal, withCredentials: true});
```

However, I still get the 401 error...

**Comment by phwegner** [comment]
Okay that way it is possible! Thanks!
