### ISSUE TITLE
definitions undefined in fhir-backend.service

### ISSUE THREAD

**Issue by pazampog** [lhncbc/fhir-obs-viewer#6]
Hi,

I was able to run the application (v 4.3.2) following the instructions.
However when I paste the URL of my testing FHIR server (i.e. the [public HAPI FHIR server](https://hapi.fhir.org/baseR4)) I see errors in the browser console highlithing _definitions_ are not properly loaded. Following the source code, I find the problem is here:
`const definitions = definitionsIndex.configByVersionName[versionName];`
in fhir-backend.service.ts (line 293).
Please can you provide a feedback/suggestion about how to initialize correctly such definitions? The guide simply states to execute "npm install" and then "npm start" but maybe some other configuration action is needed?

Thx

**Comment by plynchnlm** [comment]
Closing this, as we continued the discussion at https://github.com/lhncbc/fhir-obs-viewer/issues/5.
