### ISSUE TITLE
Pull data fails to load when filtering with some codes

### ISSUE THREAD

**Issue by pylgrim73** [lhncbc/fhir-obs-viewer#9]
Hi All,
I have made some tests to load Observations (Pull Data section) applying code filtering. In some occasion, however, such loading\filtering fails. For instance I have filtered by `Total Colhesterol` and no Observations are found. By exploring the console an error arises at line 150 of` query-params.serive.ts` (see debug_1.png and debug_2.png). As you see it seems `code` within `coding` is `undefined`. This is strange because everything is fine on FHIR server (in debug_5.png you can see an excerpt of one of the several Observations withi this code). 
If I repeat the same process, this time filtering by `Carbon Dioxide` , well everything works fine (see debug_3.png and debug_4.png). As you see this time the code is not undefined but holds the correct loinc code.

Please can you provide a feedbak on this behaviour?
Thanks a lot
<img width="896" alt="debug_1" src="https://user-images.githubusercontent.com/8290423/168225278-1efc5bce-167e-4ff4-b9dd-4d81c4c3060c.png">
<img width="404" alt="debug_2" src="https://user-images.githubusercontent.com/8290423/168225285-3f0ea340-49d7-4ccc-890c-518897486363.png">
<img width="886" alt="debug_3" src="https://user-images.githubusercontent.com/8290423/168225286-be62dc5a-6c83-4306-b081-e4f4374b6ec3.png">
<img width="623" alt="debug_4" src="https://user-images.githubusercontent.com/8290423/168225289-ba439cf3-0726-4fd5-a1fe-2e26c7db6785.png">
<img width="212" alt="debug_5" src="https://user-images.githubusercontent.com/8290423/168225291-7f284207-ba8c-4698-bc3a-f53cbf9e7bd4.png">

**Comment by plynchnlm** [comment]
Which FHIR server were you connecting to?

**Comment by pazampog** [comment]
> 

https://hapi.fhir.org/baseR4

**Comment by plynchnlm** [comment]
On that server there is http://hapi.fhir.org/baseR4/Observation/1730120, which is missing a "code".  I don't know why that is causing a problem.  We will have to look into it.  Thanks for the report.

**Comment by jcy1225** [comment]
Hi @pylgrim73,
![image](https://user-images.githubusercontent.com/80712697/176913555-9aa15572-196b-44ef-ad3c-8078d3cba26e.png)
The system now displays "display | code | system" for Observation codes that have a duplicate display. You should see something like above list with no console error when you search for `total cholesterol`. Specify the code in "Define Cohort" step to guarantee there are observations to be loaded in "Pull Data" step.
